import 'package:fledge_ecs/fledge_ecs.dart';

import '../components/collision_event.dart';

/// Removes [CollisionEvent] components at the end of each frame.
///
/// Collision events are frame-scoped - they're generated by
/// [CollisionDetectionSystem] and consumed by game systems within
/// the same frame, then cleaned up.
class CollisionCleanupSystem implements System {
  /// Creates a collision cleanup system.
  const CollisionCleanupSystem();

  @override
  SystemMeta get meta => SystemMeta(
        name: 'collision_cleanup',
        reads: {ComponentId.of<CollisionEvent>()},
        writes: {ComponentId.of<CollisionEvent>()},
      );

  @override
  RunCondition? get runCondition => null;

  @override
  bool shouldRun(World world) => true;

  @override
  Future<void> run(World world) async {
    // Collect entities with collision events
    final toClean = <Entity>[];
    for (final (entity, _) in world.query1<CollisionEvent>().iter()) {
      toClean.add(entity);
    }

    // Remove collision events
    for (final entity in toClean) {
      world.remove<CollisionEvent>(entity);
    }
  }
}
