import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'src/component_generator.dart';
import 'src/system_generator.dart';

/// Creates the Fledge ECS code generator.
///
/// This builder generates:
/// - Component registration code for @component annotated classes
/// - System wrappers for @system annotated functions
Builder fledgeEcsBuilder(BuilderOptions options) {
  return PartBuilder(
    [
      ComponentGenerator(),
      SystemGenerator(),
    ],
    '.g.dart',
    header: '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
        '// Generated by fledge_ecs_generator',
  );
}
