name: basic_ecs_example
description: Example usage of the Fledge ECS framework with code generation.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  fledge_ecs: ^0.2.2
  fledge_ecs_annotations: ^0.2.2

dev_dependencies:
  build_runner: ^2.4.0
  fledge_ecs_generator: ^0.2.2
  lints: ^6.0.0
